In [3]:
import pandas as pd
from matplotlib import pyplot as plt
import sqlite3 as sql

In [4]:
# read in the data from xlsx
df = pd.read_excel(
   '/Users/georgehayward/Hayward Dropbox/George Hayward/Hayward Data Science/GrandStreetDems/data_lab/grand_street_dems/data/2026-03-01/VoterData_AssemblyDistrict65.xlsx'
)

In [5]:
df.head(10)

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414668071,JOW,ALEXANDER,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,NaN,ALEXANDER.JOW@GMAIL.COM,19950714,20241001,A,DEM,R,NaN,20241105.0
1,414424984,RAMAKRISHNAN,HARI,NaN,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,2247176336,HARIS500@GMAIL.COM,20000805,20230922,A,DEM,R,20230922.0,20251104.0
2,414325345,SINCLAIR,CAITLIN,A,NaN,Manhattan,20,BROAD STREET,NaN,NEW YORK,...,1,NaN,NaN,19960316,20221108,A,REP,R,20221108.0,NaN
3,414887521,SAMUELSEN,HALEY,N,NaN,Manhattan,20,BROAD STREET,1001,NEW YORK,...,1,281-660-7394,HSAMUELSEN@COMCAST.NET,20010618,20250422,A,REP,R,NaN,NaN
4,413143937,RAHMAN,GELECIA,A,NaN,Manhattan,20,BROAD STREET,1002,NEW YORK,...,1,NaN,NaN,19840720,20180730,A,DEM,R,20240507.0,20250624.0
5,414390001,KONTYKO,KAITLIN,A,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,1,NaN,kakontyko@gmail.com,19881025,20230614,A,DEM,R,NaN,20251104.0
6,414389887,YU,ALBERT,S,NaN,Manhattan,20,BROAD STREET,1006,NEW YORK,...,1,NaN,albertyu17@gmail.com,19890107,20230614,A,DEM,R,NaN,20251104.0
7,414515985,SHEU,ANDREW,J,NaN,Manhattan,20,BROAD STREET,1012,NEW YORK,...,1,NaN,NaN,19900613,20240402,A,BLK,R,NaN,NaN
8,412822698,HAJJAR,ZACKARY,G,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,1,917-626-5625,zhajjar@yahoo.com,19990531,20170609,A,DEM,R,20170612.0,20241105.0
9,414134286,PANGILINAN,ADRIAN,B,NaN,Manhattan,20,BROAD STREET,1015,NEW YORK,...,1,201-654-5408,ADRIAN.PANGILINAN@GMAIL.COM,19941125,20210924,A,DEM,R,NaN,20251104.0

In [6]:
for i in df.columns:
    print(i)

VSN
LastName
FirstName
MiddleInitial
NameSuffix
Borough
RegStreetNumber
RegStreetName
RegUnitNumber
RegCity
RegZipCode
MailingAddress1
MailingAddress2
MailingAddress3
MailingAddress4
AssemblyDistrict
ElectionDistrict
CongressionalDistrict
CouncilDistrict
SenateDistrict
CivilCourtDistrict
JudicialDistrict
PhoneNumber
EmailAddress
BirthDate
RegistrationDate
StatusCode
PoliticalParty
VoterType
EffectiveStatusChangeDate
LastElectionVotedIn

In [7]:
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")

Total rows: 85824
Total columns: 31

In [8]:
conn = sql.connect("ad65_voters.db")

In [9]:
df.to_sql("voters", conn, if_exists='replace', index=False)

85824

In [10]:
# Youth voters (born after 2000) with email addresses
youth_select = pd.read_sql_query("""
select * from voters 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- proxy for born after 2000 (under 25)
;
""", conn)
youth_select

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414424984,RAMAKRISHNAN,HARI,None,None,Manhattan,20,BROAD STREET,None,NEW YORK,...,1,2247176336,HARIS500@GMAIL.COM,20000805,20230922,A,DEM,R,20230922.0,20251104.0
1,414927421,CAREY,YINGJIE,A,None,Manhattan,20,BROAD STREET,1306,NEW YORK,...,1,650-224-9533,XAN.CAREY@GMAIL.COM,20030718,20250610,A,DEM,R,NaN,NaN
2,413845018,DUCHAN,ELIZABETH,None,None,Manhattan,20,BROAD STREET,1419,NEW YORK,...,1,347-235-9711,elizabethduchan@gmail.com,20020528,20200831,A,DEM,R,NaN,20251104.0
3,415132595,WALDRON,NATALIE,None,None,Manhattan,20,BROAD STREET,201,NEW YORK,...,1,3362090815,NATALIECWALDRON@GMAIL.COM,20010803,20251104,A,DEM,R,NaN,NaN
4,414786111,SPARROW,NATASHA,A,None,Manhattan,20,BROAD STREET,2605,NEW YORK,...,1,None,nalasparrow27@gmail.com,20001127,20241030,A,DEM,R,NaN,20251104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4255,413524000,MENDEZ,EFRAIN,J,III,Manhattan,950,EAST 4 WALK,11E,NEW YORK,...,1,646-305-1049,emendez3181@gmail.com,20010318,20190927,A,DEM,R,20190930.0,20221108.0
4256,413025467,MIDDLETON TOWNS,SIDNEY,O,None,Manhattan,950,EAST 4 WALK,13I,NEW YORK,...,1,347-790-5985,sid.towns@gmail.com,20000107,20180226,A,DEM,R,20180227.0,20201103.0
4257,414259402,PITA,BRICCIO,K,None,Manhattan,950,EAST 4 WALK,4E,NEW YORK,...,1,397-827-6274,kerinpita211@gmail.com,20040211,20220825,A,DEM,R,NaN,20251104.0
4258,413760858,ISLAM,MOHAMMED,M,None,Manhattan,950,EAST 4 WALK,7B,NEW YORK,...,1,None,mufiis120@gmail.com,20020306,20200721,A,DEM,R,NaN,20251104.0
4259,413691685,LI,JUDY,None,None,Manhattan,950,EAST 4 WALK,8B,NEW YORK,...,1,917-660-1638,JUDYLIO11702@gmail.com,20020117,20200325,A,DEM,R,NaN,NaN

In [11]:
youth_select.to_csv('ad65_youth_with_email.csv', index=False, encoding='utf-8')

In [12]:
# Youth who voted recently (have a LastElectionVotedIn value)
youth_recent = pd.read_sql_query("""
select * from voters 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- proxy for born after 2000 (under 25)
and LastElectionVotedIn is not NULL
;
""", conn)
youth_recent

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414424984,RAMAKRISHNAN,HARI,None,None,Manhattan,20,BROAD STREET,None,NEW YORK,...,1,2247176336,HARIS500@GMAIL.COM,20000805,20230922,A,DEM,R,20230922.0,20251104.0
1,413845018,DUCHAN,ELIZABETH,None,None,Manhattan,20,BROAD STREET,1419,NEW YORK,...,1,347-235-9711,elizabethduchan@gmail.com,20020528,20200831,A,DEM,R,NaN,20251104.0
2,414786111,SPARROW,NATASHA,A,None,Manhattan,20,BROAD STREET,2605,NEW YORK,...,1,None,nalasparrow27@gmail.com,20001127,20241030,A,DEM,R,NaN,20251104.0
3,414758147,ARKO,ALINA,None,None,Manhattan,20,BROAD STREET,319,NEW YORK,...,1,973-223-5356,alinaarko@gmail.com,20010913,20241025,A,DEM,R,NaN,20241105.0
4,414686383,TAKIFF,GRACE,None,None,Manhattan,20,BROAD STREET,909,NEW YORK,...,1,None,grace.takiff@gmail.com,20010130,20241008,A,DEM,R,NaN,20251104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2985,415015578,MONROE,YASMIN,A,None,Manhattan,930,EAST 4 WALK,7F,NEW YORK,...,1,9172934359,YAYAJAICHSON24@GMAIL.COM,20031216,20250814,A,DEM,R,NaN,20251104.0
2986,413524000,MENDEZ,EFRAIN,J,III,Manhattan,950,EAST 4 WALK,11E,NEW YORK,...,1,646-305-1049,emendez3181@gmail.com,20010318,20190927,A,DEM,R,20190930.0,20221108.0
2987,413025467,MIDDLETON TOWNS,SIDNEY,O,None,Manhattan,950,EAST 4 WALK,13I,NEW YORK,...,1,347-790-5985,sid.towns@gmail.com,20000107,20180226,A,DEM,R,20180227.0,20201103.0
2988,414259402,PITA,BRICCIO,K,None,Manhattan,950,EAST 4 WALK,4E,NEW YORK,...,1,397-827-6274,kerinpita211@gmail.com,20040211,20220825,A,DEM,R,NaN,20251104.0
2989,413760858,ISLAM,MOHAMMED,M,None,Manhattan,950,EAST 4 WALK,7B,NEW YORK,...,1,None,mufiis120@gmail.com,20020306,20200721,A,DEM,R,NaN,20251104.0

In [13]:
youth_recent.to_csv('ad65_youth_recent_voters.csv', index=False, encoding='utf-8')

In [14]:
# Youth who haven't voted (no LastElectionVotedIn)
youth_no_vote = pd.read_sql_query("""
select * from voters 
where 1=1
and PoliticalParty in ('DEM', 'WOR')
and EmailAddress is not NULL
and BirthDate >= 20000000 -- proxy for born after 2000 (under 25)
and LastElectionVotedIn is NULL
;
""", conn)
youth_no_vote

,VSN,LastName,FirstName,MiddleInitial,NameSuffix,Borough,RegStreetNumber,RegStreetName,RegUnitNumber,RegCity,...,JudicialDistrict,PhoneNumber,EmailAddress,BirthDate,RegistrationDate,StatusCode,PoliticalParty,VoterType,EffectiveStatusChangeDate,LastElectionVotedIn
0,414927421,CAREY,YINGJIE,A,None,Manhattan,20,BROAD STREET,1306,NEW YORK,...,1,650-224-9533,XAN.CAREY@GMAIL.COM,20030718,20250610,A,DEM,R,NaN,None
1,415132595,WALDRON,NATALIE,None,None,Manhattan,20,BROAD STREET,201,NEW YORK,...,1,3362090815,NATALIECWALDRON@GMAIL.COM,20010803,20251104,A,DEM,R,NaN,None
2,415135639,RICCI,TANNER,None,None,Manhattan,20,BROAD STREET,716,NEW YORK,...,1,8583615292,TANNERRICCI138@GMAIL.COM,20000729,20251103,A,DEM,R,NaN,None
3,413081830,BELT,CHLOE,M,None,Manhattan,20,BROAD STREET,APT 504,NEW YORK,...,1,704-877-9466,chloe@belthous.com,20000526,20180526,A,DEM,R,20180530.0,None
4,414277955,NGUYEN,MELODY,Q,None,Manhattan,25,BROAD STREET,None,NEW YORK,...,1,6692409976,MELODYXNGUYEN@GMAIL.COM,20040910,20221003,A,DEM,R,20221003.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1265,414643146,HORTON,VALERIE,None,None,Manhattan,40,AVENUE D,5G,NEW YORK,...,1,347-614-3095,valhorton87@gmail.com,20051209,20240916,A,DEM,R,NaN,None
1266,413081683,BAI,KEVIN,Y,None,Manhattan,50,AVENUE D,10E,NEW YORK,...,1,646-233-9933,baikevin15@gmail.ccom,20000422,20180525,A,DEM,R,NaN,None
1267,413657752,ACEVEDO,JOEY,None,None,Manhattan,930,EAST 4 WALK,12D,NEW YORK,...,1,646-874-7230,joeyacevedo2430@gmail.com,20020218,20200221,A,DEM,R,NaN,None
1268,413491863,ALMONTE,ELIZABETH,None,None,Manhattan,930,EAST 4 WALK,2D,NEW YORK,...,1,None,ELIMALMONTE@GMAIL.COM,20010720,20190809,A,DEM,R,20190810.0,None
1269,413691685,LI,JUDY,None,None,Manhattan,950,EAST 4 WALK,8B,NEW YORK,...,1,917-660-1638,JUDYLIO11702@gmail.com,20020117,20200325,A,DEM,R,NaN,None

In [15]:
youth_no_vote.to_csv('ad65_youth_no_vote_history.csv', index=False, encoding='utf-8')